name: zerogarbage
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.8
  qrcode: ^1.0.4
  maps_launcher: ^1.2.1
  google_maps_flutter: ^0.5.28+1
  connectivity: ^0.4.8
  flushbar: ^1.10.4
  http: ^0.12.1
  flutter_icons: ^1.1.0
  outline_material_icons: ^0.1.1
  permission_handler: ^5.0.0+hotfix.6
  google_fonts: ^1.1.0
  geolocator: ^5.3.2+2
  file_picker: ^1.13.0
  http_parser: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/full.png
    - assets/images/empty.png
    - assets/images/ecodrawer.jpg

